<?php

use App\Domain\Settings\Http\Controllers\SettingsController;
use App\Domain\Invoices\Http\Controllers\InvoiceController;
use App\Domain\Companies\Http\Controllers\CompanyController;
use App\Domain\Partners\Http\Controllers\AssociationsController;
use App\Domain\Payments\Http\Controllers\PaymentsController;
use App\Domain\Reports\Http\Controllers\ReportsController;
use App\Domain\Users\Http\Controllers\UsersController;
use App\Domain\Stock\Http\Controllers\StockImportController;
use App\Domain\Audit\Http\Controllers\AuditController;
use App\Domain\Enrollment\Http\Controllers\EnrollmentLinksController;
use App\Domain\Contracts\Http\Controllers\ContractsController;
use App\Domain\Contracts\Http\Controllers\ContractTemplatesController;
use App\Domain\Contracts\Http\Controllers\DocumentRegistryController;
use App\Domain\Contracts\Http\Controllers\SupplierAnnexController;
use App\Domain\Contracts\Http\Controllers\ClientAnnexController;
use App\Domain\Contacts\Http\Controllers\ContactsController;
use App\Domain\Tools\Http\Controllers\PdfToolsController;

$router->get('/admin/setari', [SettingsController::class, 'edit']);
$router->post('/admin/setari', [SettingsController::class, 'update']);
$router->get('/admin/setari/fgo/nomenclator-judete', [SettingsController::class, 'fgoNomenclatorJudete']);
$router->post('/admin/setari/demo-generate', [SettingsController::class, 'generateDemo']);
$router->post('/admin/setari/demo-reset', [SettingsController::class, 'resetDemo']);
$router->get('/admin/utile/prelucrare-pdf', [PdfToolsController::class, 'index']);
$router->post('/admin/utile/prelucrare-pdf', [PdfToolsController::class, 'process']);
$router->get('/admin/changelog', [SettingsController::class, 'changelog']);
$router->get('/admin/audit', [AuditController::class, 'index']);
$router->get('/admin/audit/view', [AuditController::class, 'show']);
$router->get('/admin/enrollment-links', [EnrollmentLinksController::class, 'index']);
$router->get('/admin/inrolari', [EnrollmentLinksController::class, 'pending']);
$router->get('/admin/fisiere-upa', [EnrollmentLinksController::class, 'resources']);
$router->post('/admin/enrollment-links/create', [EnrollmentLinksController::class, 'create']);
$router->post('/admin/enrollment-links/disable', [EnrollmentLinksController::class, 'disable']);
$router->post('/admin/enrollment-links/regenerate', [EnrollmentLinksController::class, 'regenerate']);
$router->post('/admin/enrollment-links/lookup', [EnrollmentLinksController::class, 'lookup']);
$router->get('/admin/enrollment-links/supplier-search', [EnrollmentLinksController::class, 'supplierSearch']);
$router->get('/admin/enrollment-links/company-search', [EnrollmentLinksController::class, 'companySearch']);
$router->get('/admin/enrollment-links/supplier-info', [EnrollmentLinksController::class, 'supplierInfo']);
$router->post('/admin/enrollment-links/resources/upload', [EnrollmentLinksController::class, 'uploadResource']);
$router->post('/admin/enrollment-links/resources/delete', [EnrollmentLinksController::class, 'deleteResource']);
$router->get('/admin/enrollment-links/resources/download', [EnrollmentLinksController::class, 'downloadResource']);
$router->post('/admin/enrollment-links/approve-onboarding', [EnrollmentLinksController::class, 'approveOnboarding']);
$router->post('/admin/enrollment-links/reset-onboarding', [EnrollmentLinksController::class, 'resetOnboarding']);
$router->get('/admin/contracts', [ContractsController::class, 'index']);
$router->post('/admin/contracts/generate', [ContractsController::class, 'generate']);
$router->get('/admin/contracts/company-search', [ContractsController::class, 'companySearch']);
$router->post('/admin/contracts/upload-signed', [ContractsController::class, 'uploadSigned']);
$router->get('/admin/contracts/upload-signed/companies', [ContractsController::class, 'uploadSignedCompanies']);
$router->get('/admin/contracts/upload-signed/contracts', [ContractsController::class, 'uploadSignedContracts']);
$router->post('/admin/contracts/approve', [ContractsController::class, 'approve']);
$router->post('/admin/contracts/reset-generated-pdf', [ContractsController::class, 'resetGeneratedPdf']);
$router->get('/admin/contracts/download', [ContractsController::class, 'download']);
$router->get('/admin/anexe-furnizor', [SupplierAnnexController::class, 'index']);
$router->post('/admin/anexe-furnizor/preview', [SupplierAnnexController::class, 'preview']);
$router->post('/admin/anexe-furnizor/download', [SupplierAnnexController::class, 'download']);
$router->post('/admin/anexe-furnizor/generate-document', [SupplierAnnexController::class, 'generateDocument']);
$router->post('/admin/anexe-furnizor/delete-last-document', [SupplierAnnexController::class, 'deleteLastGeneratedDocument']);
$router->get('/admin/anexe-client', [ClientAnnexController::class, 'index']);
$router->post('/admin/anexe-client/preview', [ClientAnnexController::class, 'preview']);
$router->post('/admin/anexe-client/download', [ClientAnnexController::class, 'download']);
$router->post('/admin/anexe-client/generate-document', [ClientAnnexController::class, 'generateDocument']);
$router->post('/admin/anexe-client/delete-last-document', [ClientAnnexController::class, 'deleteLastGeneratedDocument']);
$router->get('/admin/registru-documente', [DocumentRegistryController::class, 'index']);
$router->post('/admin/registru-documente/save', [DocumentRegistryController::class, 'save']);
$router->post('/admin/registru-documente/set-start', [DocumentRegistryController::class, 'setStart']);
$router->post('/admin/registru-documente/reset-start', [DocumentRegistryController::class, 'resetStart']);
$router->get('/admin/contract-templates', [ContractTemplatesController::class, 'index']);
$router->post('/admin/contract-templates/save', [ContractTemplatesController::class, 'save']);
$router->get('/admin/contract-templates/edit', [ContractTemplatesController::class, 'edit']);
$router->post('/admin/contract-templates/update', [ContractTemplatesController::class, 'update']);
$router->post('/admin/contract-templates/duplicate', [ContractTemplatesController::class, 'duplicate']);
$router->post('/admin/contract-templates/preview', [ContractTemplatesController::class, 'preview']);
$router->get('/admin/contract-templates/download-draft', [ContractTemplatesController::class, 'downloadDraftPdf']);
$router->post('/admin/contract-templates/upload-stamp', [ContractTemplatesController::class, 'uploadStamp']);
$router->post('/admin/contract-templates/remove-stamp', [ContractTemplatesController::class, 'removeStamp']);
$router->get('/admin/contract-templates/stamp', [ContractTemplatesController::class, 'stamp']);
$router->post('/admin/contacts/create', [ContactsController::class, 'create']);
$router->post('/admin/contacts/delete', [ContactsController::class, 'delete']);

$router->get('/admin/facturi', [InvoiceController::class, 'index']);
$router->get('/admin/facturi/search', [InvoiceController::class, 'search']);
$router->get('/admin/facturi/export', [InvoiceController::class, 'export']);
$router->get('/admin/facturi/fisier', [InvoiceController::class, 'showSupplierFile']);
$router->get('/admin/facturi/print-situatie', [InvoiceController::class, 'printSituation']);
$router->get('/admin/facturi/lookup-suppliers', [InvoiceController::class, 'lookupSuppliers']);
$router->get('/admin/facturi/lookup-clients', [InvoiceController::class, 'lookupClients']);
$router->get('/admin/facturi/manual/suppliers-search', [InvoiceController::class, 'manualSupplierSearch']);
$router->get('/admin/facturi/manual/clients-search', [InvoiceController::class, 'manualClientSearch']);
$router->get('/admin/pachete-confirmate', [InvoiceController::class, 'confirmedPackages']);
$router->post('/admin/pachete-confirmate/import-saga', [InvoiceController::class, 'importSagaCsv']);
$router->get('/admin/pachete-confirmate/saga-json', [InvoiceController::class, 'sagaPackageJson']);
$router->post('/admin/pachete-confirmate/saga-pending', [InvoiceController::class, 'markSagaPending']);
$router->get('/api/saga/pachet', [InvoiceController::class, 'apiSagaPackage']);
$router->get('/api/saga/pachete', [InvoiceController::class, 'apiSagaPending']);
$router->post('/api/saga/pachet/executed', [InvoiceController::class, 'apiSagaExecuted']);
$router->post('/api/saga/pachet/imported', [InvoiceController::class, 'apiSagaImported']);
$router->get('/api/saga/pachet/imported', [InvoiceController::class, 'apiSagaImported']);
$router->get('/api/stock/import', [StockImportController::class, 'status']);
$router->post('/api/stock/import', [StockImportController::class, 'import']);
$router->get('/admin/facturi/adauga', [InvoiceController::class, 'showManual']);
$router->post('/admin/facturi/adauga', [InvoiceController::class, 'storeManual']);
$router->post('/admin/facturi/calc-totals', [InvoiceController::class, 'calcManualTotals']);
$router->get('/admin/facturi/anexa', [InvoiceController::class, 'showAviz']);
$router->get('/admin/facturi/aviz', function (): void {
    $invoiceId = isset($_GET['invoice_id']) ? (int) $_GET['invoice_id'] : 0;
    if ($invoiceId) {
        App\Support\Response::redirect('/admin/facturi/anexa?invoice_id=' . $invoiceId);
    }
    App\Support\Response::redirect('/admin/facturi/anexa');
});
$router->get('/admin/facturi/nota-comanda', [InvoiceController::class, 'showOrderNote']);
$router->get('/admin/facturi/import', [InvoiceController::class, 'showImport']);
$router->post('/admin/facturi/import', [InvoiceController::class, 'import']);
$router->post('/admin/facturi/pachete', [InvoiceController::class, 'packages']);
$router->post('/admin/facturi/ajustare-totaluri', [InvoiceController::class, 'applyTotalsAdjustment']);
$router->post('/admin/facturi/muta-linie', [InvoiceController::class, 'moveLine']);
$router->post('/admin/facturi/split-linie', [InvoiceController::class, 'splitLine']);
$router->post('/admin/facturi/genereaza', [InvoiceController::class, 'generateInvoice']);
$router->post('/admin/facturi/incarca-fisier', [InvoiceController::class, 'uploadSupplierFile']);
$router->post('/admin/facturi/deblocheaza-client', [InvoiceController::class, 'unlockClient']);
$router->post('/admin/facturi/redenumeste-pachet', [InvoiceController::class, 'renamePackage']);
$router->post('/admin/facturi/print', [InvoiceController::class, 'printInvoice']);
$router->post('/admin/facturi/print-storno', [InvoiceController::class, 'printStornoInvoice']);
$router->post('/admin/facturi/storno', [InvoiceController::class, 'stornoInvoice']);
$router->post('/admin/facturi/refacere', [InvoiceController::class, 'rebuildInvoice']);
$router->post('/admin/facturi/refacere/genereaza', [InvoiceController::class, 'generateAdjustmentInvoice']);
$router->post('/admin/facturi/sterge', [InvoiceController::class, 'delete']);

$router->get('/admin/incasari', [PaymentsController::class, 'indexIn']);
$router->get('/admin/incasari/adauga', [PaymentsController::class, 'createIn']);
$router->post('/admin/incasari/adauga', [PaymentsController::class, 'storeIn']);
$router->get('/admin/incasari/istoric', [PaymentsController::class, 'historyIn']);
$router->post('/admin/incasari/sterge', [PaymentsController::class, 'deleteIn']);
$router->get('/admin/plati', [PaymentsController::class, 'indexOut']);
$router->get('/admin/plati/adauga', [PaymentsController::class, 'createOut']);
$router->post('/admin/plati/adauga', [PaymentsController::class, 'storeOut']);
$router->get('/admin/plati/istoric', [PaymentsController::class, 'historyOut']);
$router->get('/admin/plati/print', [PaymentsController::class, 'printOut']);
$router->get('/admin/plati/export', [PaymentsController::class, 'exportOut']);
$router->post('/admin/plati/ordine-plata', [PaymentsController::class, 'exportPaymentOrder']);
$router->post('/admin/plati/sterge', [PaymentsController::class, 'deleteOut']);
$router->post('/admin/plati/email-azi', [PaymentsController::class, 'sendDailyEmails']);

$router->get('/admin/rapoarte/cashflow', [ReportsController::class, 'cashflow']);
$router->get('/admin/rapoarte/cashflow/export', [ReportsController::class, 'exportCashflow']);
$router->get('/admin/rapoarte/cashflow/pdf', [ReportsController::class, 'cashflowPdf']);

$router->get('/admin/utilizatori', [UsersController::class, 'index']);
$router->get('/admin/utilizatori/adauga', [UsersController::class, 'create']);
$router->post('/admin/utilizatori/adauga', [UsersController::class, 'store']);
$router->get('/admin/utilizatori/edit', [UsersController::class, 'edit']);
$router->post('/admin/utilizatori/update', [UsersController::class, 'update']);
$router->post('/admin/utilizatori/sterge', [UsersController::class, 'delete']);
$router->get('/admin/profil', [UsersController::class, 'profile']);
$router->post('/admin/profil/parola', [UsersController::class, 'updatePassword']);

$router->get('/admin/companii', [CompanyController::class, 'index']);
$router->get('/admin/companii/edit', [CompanyController::class, 'edit']);
$router->post('/admin/companii/save', [CompanyController::class, 'save']);
$router->post('/admin/companii/openapi', [CompanyController::class, 'lookupOpenApi']);

$router->get('/admin/asocieri', [AssociationsController::class, 'index']);
$router->post('/admin/asocieri/salveaza', [AssociationsController::class, 'save']);
$router->post('/admin/asocieri/comision-default', [AssociationsController::class, 'saveDefaultCommission']);
$router->post('/admin/asocieri/solicitari/aproba', [AssociationsController::class, 'approveRequest']);
$router->post('/admin/asocieri/solicitari/refuza', [AssociationsController::class, 'rejectRequest']);
$router->post('/admin/asocieri/sterge', [AssociationsController::class, 'delete']);
